@host = http://localhost:1234/api
###
GET {{host}}/drones/
###
GET {{host}}/drones/available/

###
GET {{host}}/drones/1/medications

###
GET {{host}}/drones/DRN001/battery

###
POST {{host}}/drones/
Content-Type:application/json

{
    "serialNumber": "DRN014",
    "model": "Lightweight",
    "state": "IDLE",
    "weightLimit": "101",
    "batteryCapacity": "100"
}

###
POST {{host}}/drones/1/medications
Content-Type:application/json

{

}